server.port=${PORT:8080}
spring.application.name=CodeSync

# WebSocket
codesync.websocket.allowed-origins=*

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:codesync}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:codesync}
spring.datasource.password=${DATABASE_PASSWORD:codesync_password}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

# H2 disabled
spring.h2.console.enabled=false

# Piston
codesync.piston.base-url=${PISTON_BASE_URL:http://localhost:2000/api/v2}